### ISSUE TITLE
UI for setting check timeout 

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-check#54]
> Extracted from https://github.com/ipfs/ipfs-check/pull/47

If DHT is still being mapped, or we test CID Without providers, it will wait forever, e.g. here its 15minutes before showing result to user:

> ![2024-08-29_19-55](https://github.com/user-attachments/assets/afc27aef-417b-4366-9c44-619ae2843fe5)

## Proposed improvements

- Have some sane timeout by default (e.g. 1 minute)
- When button is pressed, start the countdown, so user knows  how long test will work in the worst case
- Have `<input type="range"` allowing user to adjust timeout (e.g. between 30 seconds and 15 minutes?), and pass it to backend

**Comment by lidel** [comment]
I don't think this will happen often, I think the long wait happens only when backend was just restarted, and Amino DHT is being mapped by FullRT client. 

I will improve console output in separate PR.

**Comment by 2color** [comment]
Thanks for pointing this out! This is indeed a problem when you start it locally and it runs the accelerated DHT (aka FullRT) by default.

> Have <input type="range" allowing user to adjust timeout (e.g. between 30 seconds and 15 minutes?), and pass it to backend

We can also implement this on the frontend with an AbortSignal https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static which we'd handle on the backend using the context
